### ISSUE TITLE
Issue with project

### ISSUE THREAD

**Issue by gptonly** [khyrulAlam/react-firebase-chat#37]
Error on replit:
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/react-firebase-chat-1/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/react-firebase-chat-1/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/runner/react-firebase-chat-1/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/runner/react-firebase-chat-1/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/runner/react-firebase-chat-1/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/runner/react-firebase-chat-1/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/runner/react-firebase-chat-1/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/runner/react-firebase-chat-1/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/runner/react-firebase-chat-1/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/react-firebase-chat-1/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/react-firebase-chat-1/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/runner/react-firebase-chat-1/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/runner/react-firebase-chat-1/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/runner/react-firebase-chat-1/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/runner/react-firebase-chat-1/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/runner/react-firebase-chat-1/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/runner/react-firebase-chat-1/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
exit status 1

**Comment by khyrulAlam** [comment]
Check your local node version. It should be less than 16.
